// Re-export Prisma types for convenience
export type {
  User,
  Tenant,
  Membership,
  Permission,
  RolePermission,
  LinkedInAccount,
  Tender,
  Publication,
  Candidate,
  Experience,
  CVTemplate,
  CVExport,
  Plan,
  Subscription,
  FileObject,
  Workflow,
  IntegrationEvent,
  AuditLog,
  Account,
  Session,
  VerificationToken,
} from '@prisma/client'
